#include "phd_types.h"
#include "phd_types_meta.h"

#define CHOICE_TO_STRUCT(UNION, CHOICE, STRUCT) \
	if (union_type == UNION && choice == CHOICE) { \
		new_fmt = & ## STRUCT ## _fmt; \
	}

CHOICE_TO_STRUCT(MESG_UNION, ROIV_CMIP_EVENT_REPORT_CHOSEN, EventReportArgumentSimple)
CHOICE_TO_STRUCT(MESG_UNION, ROIV_CMIP_CONFIRMED_EVENT_REPORT_CHOSEN, EventReportArgumentSimple)
CHOICE_TO_STRUCT(MESG_UNION, ROIV_CMIP_GET_CHOSEN, GetArgumentSimple)
CHOICE_TO_STRUCT(MESG_UNION, ROIV_CMIP_SET_CHOSEN, SetArgumentSimple)
CHOICE_TO_STRUCT(MESG_UNION, ROIV_CMIP_CONFIRMED_SET_CHOSEN, SetArgumentSimple)
CHOICE_TO_STRUCT(MESG_UNION, ROIV_CMIP_ACTION_CHOSEN, ActionArgumentSimple)
CHOICE_TO_STRUCT(MESG_UNION, ROIV_CMIP_CONFIRMED_ACTION_CHOSEN, ActionArgumentSimple)
CHOICE_TO_STRUCT(MESG_UNION, RORS_CMIP_CONFIRMED_EVENT_REPORT_CHOSEN, EventReportResultSimple)
CHOICE_TO_STRUCT(MESG_UNION, RORS_CMIP_GET_CHOSEN, GetResultSimple)
CHOICE_TO_STRUCT(MESG_UNION, RORS_CMIP_CONFIRMED_SET_CHOSEN, SetResultSimple)
CHOICE_TO_STRUCT(MESG_UNION, RORS_CMIP_CONFIRMED_ACTION_CHOSEN, ActionResultSimple)
CHOICE_TO_STRUCT(MESG_UNION, ROER_CHOSEN, ErrorResult)
CHOICE_TO_STRUCT(MESG_UNION, RORJ_CHOSEN, RejectResult)

CHOICE_TO_STRUCT(APDU_UNION, AARQ_CHOSEN, AARQ_apdu)
CHOICE_TO_STRUCT(APDU_UNION, AARE_CHOSEN, AARE_apdu)
CHOICE_TO_STRUCT(APDU_UNION, RLRQ_CHOSEN, RLRQ_apdu)
CHOICE_TO_STRUCT(APDU_UNION, RLRE_CHOSEN, RLRE_apdu)
CHOICE_TO_STRUCT(APDU_UNION, ABRT_CHOSEN, ABRT_apdu)
CHOICE_TO_STRUCT(APDU_UNION, PRST_CHOSEN, octet_string)

CHOICE_TO_STRUCT(ENUM_UNION, TEXT_STRING_CHOSEN, octet_string)

CHOICE_TO_STRUCT(SEGM_UNION, SEGM_ID_LIST_CHOSEN, SegmIdList)
CHOICE_TO_STRUCT(SEGM_UNION, ABS_TIME_RANGE_CHOSEN, AbsTimeRange)