#define struct_Any								0
#define struct_TYPE								1
#define struct_AVA_Type							2
#define struct_AttributeList					3
#define struct_AttributeIdList					4
#define struct_HighResRelativeTime				5
#define struct_AbsoluteTimeAdjust				6
#define struct_AbsoluteTime						7
#define struct_octet_string						8
#define struct_SystemModel						9
#define struct_ProdSpecEntry					10
#define struct_ProductionSpec					11
#define struct_BatMeasure						12
#define struct_NuObsValue						13
#define struct_NuObsValueCmp					14
#define struct_SampleType						15
#define struct_SaSpec							16
#define struct_ScaleRangeSpec8					17
#define struct_ScaleRangeSpec16					18
#define struct_ScaleRangeSpec32					19
#define struct_EnumVal							20
#define struct_EnumObsValue						21
#define struct_AttrValMapEntry					22
#define struct_AttrValMap						23
#define struct_HandleAttrValMapEntry			24
#define struct_HandleAttrValMap					25
#define struct_SetTimeInvoke					26
#define struct_SegmIdList						27
#define struct_AbsTimeRange						28
#define struct_SegmentInfo						29
#define struct_SegmentInfoList					30
#define struct_SegmSelection					31
#define struct_SegmEntryElem					32
#define struct_SegmEntryElemList				33
#define struct_PmSegmentEntryMap				34
#define struct_SegmElemStaticAttrEntry			35
#define struct_PmSegmElemStaticAttrList			36
#define struct_TrigSegmDataXferReq				37
#define struct_TrigSegmDataXferRsp				38
#define struct_SegmDataEventDescr				39
#define struct_SegmentDataEvent					40
#define struct_SegmentDataResult				41
#define struct_SegmentStatisticEntry			42
#define struct_SegmentStatistics				43
#define struct_ObservationScan					44
#define struct_UUID_Ident						45
#define struct_DataProto						46
#define struct_DataProtoList					47
#define struct_AARQ_apdu						48
#define struct_AARE_apdu						49
#define struct_RLRQ_apdu						50
#define struct_RLRE_apdu						51
#define struct_ABRT_apdu						52
#define struct_EventReportArgumentSimple		53
#define struct_GetArgumentSimple				54
#define struct_AttributeModEntry				55
#define struct_ModificationList					56
#define struct_SetArgumentSimple				57
#define struct_ActionArgumentSimple				58
#define struct_EventReportResultSimple			59
#define struct_GetResultSimple					60
#define struct_TypeVer							61
#define struct_TypeVerList						62
#define struct_SetResultSimple					63
#define struct_ActionResultSimple				64
#define struct_ErrorResult						65
#define struct_RejectResult						66
#define struct_DATA_apdu_message				67
#define struct_DATA_apdu						68
#define struct_APDU								69
#define struct_DataReqModeCapab					70
#define struct_PhdAssociationInformation		71
#define struct_ManufSpecAssociationInformation	72
#define struct_MdsTimeInfo						73
#define struct_MetricStructureSmall				74
#define struct_MetricIdList						75
#define struct_SupplementalTypeList				76
#define struct_ObservationScanList				77
#define struct_ScanReportPerVar					78
#define struct_ScanReportPerVarList				79
#define struct_ScanReportInfoMPVar				80
#define struct_ObservationScanFixed				81
#define struct_ObservationScanFixedList			82
#define struct_ScanReportPerFixed				83
#define struct_ScanReportPerFixedList			84
#define struct_ScanReportInfoMPFixed			85
#define struct_ScanReportInfoVar				86
#define struct_ScanReportInfoFixed				87
#define struct_ScanReportInfoGroupedList		88
#define struct_ScanReportInfoGrouped			89
#define struct_ScanReportPerGrouped				90
#define struct_ScanReportPerGroupedList			91
#define struct_ScanReportInfoMPGrouped			92
#define struct_ConfigObject						93
#define struct_ConfigObjectList					94
#define struct_ConfigReport						95
#define struct_ConfigReportRsp					96
#define struct_ASN1_HANDLEList					97
#define struct_DataRequest						98
#define struct_DataResponse						99
#define struct_SimpleNuObsValueCmp				100
#define struct_BasicNuObsValueCmp				101