#include <string.h>

#define STR_TO_STRUCT(A) \
	if (strcmp(#A, string) == 0) { \
		new_fmt = & ## A ## _fmt; \
	}

#define STR_TO_STRUCT2(A, B) \
	if (strcmp(#A, string) == 0) { \
		new_fmt = & ## B ## _fmt; \
	}

STR_TO_STRUCT(Any)
STR_TO_STRUCT(TYPE)
STR_TO_STRUCT(AVA_Type)
STR_TO_STRUCT(AttributeList)
STR_TO_STRUCT(AttributeIdList)
STR_TO_STRUCT(HighResRelativeTime)
STR_TO_STRUCT(AbsoluteTimeAdjust)
STR_TO_STRUCT(AbsoluteTime)
STR_TO_STRUCT(octet_string)
STR_TO_STRUCT(SystemModel)
STR_TO_STRUCT(ProdSpecEntry)
STR_TO_STRUCT(ProductionSpec)
STR_TO_STRUCT(BatMeasure)
STR_TO_STRUCT(NuObsValue)
STR_TO_STRUCT(NuObsValueCmp)
STR_TO_STRUCT(SampleType)
STR_TO_STRUCT(SaSpec)
STR_TO_STRUCT(ScaleRangeSpec8)
STR_TO_STRUCT(ScaleRangeSpec16)
STR_TO_STRUCT(ScaleRangeSpec32)
STR_TO_STRUCT(EnumVal)
STR_TO_STRUCT(EnumObsValue)
STR_TO_STRUCT(AttrValMapEntry)
STR_TO_STRUCT(AttrValMap)
STR_TO_STRUCT(HandleAttrValMapEntry)
STR_TO_STRUCT(HandleAttrValMap)
STR_TO_STRUCT(SetTimeInvoke)
STR_TO_STRUCT(SegmIdList)
STR_TO_STRUCT(AbsTimeRange)
STR_TO_STRUCT(SegmentInfo)
STR_TO_STRUCT(SegmentInfoList)
STR_TO_STRUCT(SegmSelection)
STR_TO_STRUCT(SegmEntryElem)
STR_TO_STRUCT(SegmEntryElemList)
STR_TO_STRUCT(PmSegmentEntryMap)
STR_TO_STRUCT(SegmElemStaticAttrEntry)
STR_TO_STRUCT(PmSegmElemStaticAttrList)
STR_TO_STRUCT(TrigSegmDataXferReq)
STR_TO_STRUCT(TrigSegmDataXferRsp)
STR_TO_STRUCT(SegmDataEventDescr)
STR_TO_STRUCT(SegmentDataEvent)
STR_TO_STRUCT(SegmentDataResult)
STR_TO_STRUCT(SegmentStatisticEntry)
STR_TO_STRUCT(SegmentStatistics)
STR_TO_STRUCT(ObservationScan)
STR_TO_STRUCT(UUID_Ident)
STR_TO_STRUCT(DataProto)
STR_TO_STRUCT(DataProtoList)
STR_TO_STRUCT(AARQ_apdu)
STR_TO_STRUCT(AARE_apdu)
STR_TO_STRUCT(RLRQ_apdu)
STR_TO_STRUCT(RLRE_apdu)
STR_TO_STRUCT(ABRT_apdu)
STR_TO_STRUCT(EventReportArgumentSimple)
STR_TO_STRUCT(GetArgumentSimple)
STR_TO_STRUCT(AttributeModEntry)
STR_TO_STRUCT(ModificationList)
STR_TO_STRUCT(SetArgumentSimple)
STR_TO_STRUCT(ActionArgumentSimple)
STR_TO_STRUCT(EventReportResultSimple)
STR_TO_STRUCT(GetResultSimple)
STR_TO_STRUCT(TypeVer)
STR_TO_STRUCT(TypeVerList)
STR_TO_STRUCT(SetResultSimple)
STR_TO_STRUCT(ActionResultSimple)
STR_TO_STRUCT(ErrorResult)
STR_TO_STRUCT(RejectResult)
STR_TO_STRUCT(DATA_apdu_message)
STR_TO_STRUCT(DATA_apdu)
STR_TO_STRUCT(APDU)
STR_TO_STRUCT(DataReqModeCapab)
STR_TO_STRUCT(PhdAssociationInformation)
STR_TO_STRUCT(ManufSpecAssociationInformation)
STR_TO_STRUCT(MdsTimeInfo)
STR_TO_STRUCT(MetricStructureSmall)
STR_TO_STRUCT(MetricIdList)
STR_TO_STRUCT(SupplementalTypeList)
STR_TO_STRUCT(ObservationScanList)
STR_TO_STRUCT(ScanReportPerVar)
STR_TO_STRUCT(ScanReportPerVarList)
STR_TO_STRUCT(ScanReportInfoMPVar)
STR_TO_STRUCT(ObservationScanFixed)
STR_TO_STRUCT(ObservationScanFixedList)
STR_TO_STRUCT(ScanReportPerFixed)
STR_TO_STRUCT(ScanReportPerFixedList)
STR_TO_STRUCT(ScanReportInfoMPFixed)
STR_TO_STRUCT(ScanReportInfoVar)
STR_TO_STRUCT(ScanReportInfoFixed)
STR_TO_STRUCT(ScanReportInfoGroupedList)
STR_TO_STRUCT(ScanReportInfoGrouped)
STR_TO_STRUCT(ScanReportPerGrouped)
STR_TO_STRUCT(ScanReportPerGroupedList)
STR_TO_STRUCT(ScanReportInfoMPGrouped)
STR_TO_STRUCT(ConfigObject)
STR_TO_STRUCT(ConfigObjectList)
STR_TO_STRUCT(ConfigReport)
STR_TO_STRUCT(ConfigReportRsp)
STR_TO_STRUCT(ASN1_HANDLEList)
STR_TO_STRUCT(DataRequest)
STR_TO_STRUCT(DataResponse)
STR_TO_STRUCT(SimpleNuObsValueCmp)
STR_TO_STRUCT(BasicNuObsValueCmp)

STR_TO_STRUCT2(AVA_Type*, AVA_Type)
STR_TO_STRUCT2(ProdSpecEntry*, ProdSpecEntry)
STR_TO_STRUCT2(NuObsValue*, NuObsValue)
STR_TO_STRUCT2(AttrValMapEntry*, AttrValMapEntry)
STR_TO_STRUCT2(HandleAttrValMapEntry*, HandleAttrValMapEntry)
STR_TO_STRUCT2(SegmentInfo*, SegmentInfo)
STR_TO_STRUCT2(SegmEntryElem*, SegmEntryElem)
STR_TO_STRUCT2(SegmElemStaticAttrEntry*, SegmElemStaticAttrEntry)
STR_TO_STRUCT2(SegmentStatisticEntry*, SegmentStatisticEntry)
STR_TO_STRUCT2(DataProto*, DataProto)
STR_TO_STRUCT2(AttributeModEntry*, AttributeModEntry)
STR_TO_STRUCT2(TypeVer*, TypeVer)
STR_TO_STRUCT2(TYPE*, TYPE)
STR_TO_STRUCT2(ObservationScan*, ObservationScan)
STR_TO_STRUCT2(ScanReportPerVar*, ScanReportPerVar)
STR_TO_STRUCT2(ObservationScanFixed*, ObservationScanFixed)
STR_TO_STRUCT2(ScanReportPerFixed*, ScanReportPerFixed)
STR_TO_STRUCT2(octet_string*, octet_string)
STR_TO_STRUCT2(ScanReportPerGrouped*, ScanReportPerGrouped)
STR_TO_STRUCT2(ConfigObject*, ConfigObject)

#undef STR_TO_STRUCT
#undef STR_TO_STRUCT2